language: c

compiler:
  - gcc

notifications:
  email:
    - pombredanne@gmail.com

before_install:
  - sudo apt-get update
  - sudo apt-get install mingw32 wine

install:
  - source setup-w32.sh

script:
  - build.sh

after_success:
  ls -alR
