language: c

compiler:
  - gcc

notifications:
  email:
    - pombredanne@gmail.com

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq mingw32 wine

install:
  - export HOST_TARGET=i586-mingw32msvc
  - source setup.sh

script:
  - PACKAGE_NAME=glibc PACKAGE_VERSION=2.17 PACKAGE_URL=http://ftp.gnu.org/gnu/glibc build2
  - PACKAGE_NAME=zlib PACKAGE_VERSION=1.2.8 PACKAGE_URL=http://zlib.net build2
  - PACKAGE_NAME=file PACKAGE_VERSION=5.14 PACKAGE_URL=ftp://ftp.astron.com/pub/file build2
