language: c

compiler:
  - gcc

notifications:
  email:
    - pombredanne@gmail.com

before_install:
  - sudo apt-get update
  - sudo apt-get install mingw32 wine

install:
  - source setup-w32.sh

script:
  - PACKAGE_NAME=zlib PACKAGE_VERSION=1.2.8 PACKAGE_URL=http://zlib.net build
  - PACKAGE_NAME=file PACKAGE_VERSION=5.14 PACKAGE_URL=ftp://ftp.astron.com/pub/file build

after_success:
  ls -alR
